app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('sendmail', views.sendmail, name='sendmail'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('change-password/', views.change_password, name='change_password'),
    path('edituser/', views.edituser, name='edituser'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('profiles/', views.ProfileListView.as_view(), name='profiles'),  
    path('profile/<int:pk>', views.ProfileDetailView.as_view(), name='profile-detail'),
    path('profile/add/', views.ProfileCreate.as_view(), name='profile-add'),
    path('profile/<int:pk>/', views.ProfileUpdate.as_view(), name='profile-update'),
    path('profile/<int:pk>/delete/', views.ProfileDelete.as_view(), name='profile-delete'),
    path('vaccines/', views.VaccineListView.as_view(), name='vaccines'),  
    path('vaccine/<int:pk>', views.VaccineDetailView.as_view(), name='vaccine-detail'), 
    path('vaccine/add/', views.VaccineCreate.as_view(), name='vaccine-add'),
    path('vaccine/<int:pk>/', views.VaccineUpdate.as_view(), name='vaccine-update'),
    path('vaccine/<int:pk>/delete/', views.VaccineDelete.as_view(), name='vaccine-delete'), 
    path('immunizations/', views.ImmunizationListView.as_view(), name='immunizations'),  
    path('immunization/<int:pk>', views.ImmunizationDetailView.as_view(), name='immunization-detail'),
    path('immunization/add/', views.ImmunizationCreate.as_view(), name='immunization-add'),
    path('immunization/<int:pk>/', views.ImmunizationUpdate.as_view(), name='immunization-update'),
    path('immunization/<int:pk>/delete/', views.ImmunizationDelete.as_view(), name='immunization-delete'),    
]

pethealthpassport/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Health Passport Adminstration"
admin.site.site_title = "Health Passport Admin Portal"
admin.site.index_title = "Welcome to Health Passport Portal"

app/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from datetime import datetime
from datetime import date
from django.contrib.auth.models import User

class Vaccine(models.Model):
    DISEASE_TYPE_CHOICES = [('Canine parainfluenza virus', 'Canine parainfluenza virus'),('Canine Bordetella bronchiseptica', 'Canine Bordetella bronchiseptica'),('Canine Leptospira', 'Canine Leptospira'),('Canine Borrelia', 'Canine Borrelia'), ('Canine enteric coronavirus', 'Canine enteric coronavirus'), ('Canine distemper virus', 'Canine distemper virus'), ('Canine adenovirus', 'Canine adenovirus'), ('Canine parvovirus type 2', 'Canine parvovirus type 2'), ('Canine Rabies virus', 'Canine Rabies virus'), ('Feline parvovirus', 'Feline parvovirus'), ('Feline leukaemia virus', 'Feline leukaemia virus'), ('Feline infectious peritonitis', 'Feline infectious peritonitis'), ('Feline herpesvirus type 1', 'Feline herpesvirus type 1'), ('Feline Chlamydia felis', 'Feline Chlamydia felis'), ('Feline calicivirus', 'Feline calicivirus'), ('Feline Bordetella', 'Feline Bordetella'), ('Feline Rabies virus', 'Feline Rabies virus'), ('Feline immunodeficiency virus', 'Feline immunodeficiency virus')] 
    vaccine_name = models.CharField(max_length=200, choices=DISEASE_TYPE_CHOICES, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def get_absolute_url(self):
        return reverse('vaccine-detail', args=[str(self.id)])

    def __str__(self):
        return self.vaccine_name

class Profile(models.Model):
    MEMBER_CHOICES = [('Dog', 'Dog'),('Cat', 'Cat'),('Other', 'Other')]
    family_name = models.CharField(max_length=200)
    pet_name = models.CharField(max_length=200)
    pet_microchip_id = models.CharField(max_length=200)
    date_of_birth = models.DateField(default=None)
    doctor_name_contact = models.CharField(max_length=200, blank=True)
    family_member_type = models.CharField(max_length=200, choices=MEMBER_CHOICES, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    owner = models.ForeignKey(User, null=True, blank=True, editable=False, on_delete=models.CASCADE)
    
    def get_absolute_url(self):
        return reverse('profile-detail', args=[str(self.id)])

    def __str__(self):
        return self.pet_name

    def calculate_age(self):
        today = date.today()
        age = today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
        return age

    def profile_exists_by_owner(self):
        if self.objects.filter(owner=self.request.user).exists():
            return True
        else:
            return False
      
class Immunization(models.Model):
    vaccine = models.ForeignKey(Vaccine, on_delete=models.CASCADE, blank=True, null=True) 
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)    
    expired_by = models.DateField(null=True, blank=True)
    date_administered = models.DateField(null=True, blank=True)
    administered_by = models.CharField(max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    owner = models.ForeignKey(User, null=True, blank=True, editable=False, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('immunization-detail', args=[str(self.id)])

    def __str__(self):
        return self.vaccine.vaccine_name 

    def vaccine_expired(self):
        return self.expired_by < datetime.now().date()  

app/templates/app/about.html
{% include 'app/partials/base.html' %}

<div class="container">
    <div class="cards-show">
        <div class="card">
            <h5 class="card-header"><strong>About Us</strong></h5>
            <div class="card-body">
                <p class="card-text text-left">Health Passport was developed to solve a real world problem of not having
                    vaccination & critical health data in a central location.</p>
                <p class="card-text text-left">We want to provide a digital solutuon that helps people stay organized
                    with their vaccinations and critical health information as well as
                    manage records for their families.</p>
                <p class="card-text text-left">We hope that this solution helps people in all locations and from all
                    walks of life keep themselves and their families safe and healthy.</p>
            </div>
        </div>
    </div>
    <hr>
    <a class="btn btn-flat" href="{% url 'index' %}">Back to Home</a>
</div>

app/templates/app/immunization_delete_form.html
{% include 'app/partials/base.html' %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="cards-show m-5">
        <h5 class="card-header text-center">
            <strong>Delete {{ object }}</strong>
        </h5>
        <form class='form-format' method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm">
        </form>
    </div>
    <hr>
    <a class="btn btn-flat" href="{% url 'profile-detail' immunization.profile.id %}">Back to Profile</a>
</div>

app/templates/app/immunization_detail.html
{% include 'app/partials/base.html' %}

<div class="container">
    <div class="cards-show">
        <div class="card">
            <h5 class="card-header"><strong>{{ immunization.vaccine.vaccine_name }} Immunization / Vaccination
                    Detail</strong>
            </h5>
            <div class="card-body">
                <ul class="list-inline-profile">
                    <li><strong>Name:</strong> <a
                            href="{{ immunization.vaccine.get_absolute_url }}">{{ immunization.vaccine.vaccine_name }}</a>
                    </li>
                    <li><strong>Vaccine Name:</strong> {{ immunization.vaccine.vaccine_name }}</li>
                    <li><strong>Date Administered:</strong> {{ immunization.date_administered }}</li>
                    <li><strong>Administered By:</strong> {{ immunization.administered_by }}</li>
                    <li><strong>Expires:</strong> {{ immunization.expired_by }}</li>
                </ul>
            </div>
        </div>
    </div>
    <hr>
    <a class="btn btn-flat" href="{% url 'profile-detail' immunization.profile.id %}">Back to Pet Profile</a>
</div>

app/templates/app/immunization_list.html
{% include 'app/partials/base.html' %}

<h1>Immunizations</h1>

app/templates/app/immunization_update_form.html
{% include 'app/partials/base.html' %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="cards-show m-5">
        <h5 class="card-header text-center">
            <strong>Update {{ object }}</strong>
        </h5>
        <form class='form-format' method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-flat" type="submit" value="Update">
        </form>
    </div>
    <hr>
    <a class="btn btn-flat" href="{% url 'profile-detail' immunization.profile.id %}">Back to Pet Profile</a>
</div>

app/templates/app/index.html
{% include 'app/partials/base.html' %}

<div class="banner"
    style="background-image: linear-gradient(rgba(0,0,0,0.0),rgba(0,0,0,0.95)), url(https://images.unsplash.com/photo-1504208434309-cb69f4fe52b0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80);">
    <!-- Photo by Lynda B on Unsplash -->
    <div class="container">
        <h1>Health Passport - Pet Edition <i class="fas fa-paw" style="font-size: 30px; color: white"></i></h1>
        <p>You & your pet's digital health & vaccination tracker</p>
    </div>
</div>

<div class="container">
    <div class="cards-show">
        <div class="card">
            <h5 class="card-header"><strong>Health & Vaccination Tracker</strong></h5>
            <div class="card-body">
                <h5 class="card-text">Managing vaccination records has never been easier with Health Passport</h5>
                <br>
                <div class="feature-list">
                    <ul class="list-inline">
                        <li><i class="far fa-file fa-fw" id="icon"></i>Track Digital Vaccine Records</li>
                        <li><i class="far fa-bell fa-fw" id="icon"></i>Get Alerts & Reminders</li>
                        <li><i class="far fa-eye fa-fw" id="icon"></i>Manage Upcoming Vaccines</li>
                    </ul>
                </div>
                <h5 class="card-text">Follow 3 easy steps</h5>
                <br>
                <div class="container">
                    <div class="row">
                        <div class="col-sm">
                            <i class="fas fa-sign-in-alt fa-3x"></i>
                            <p><strong>1:</strong> Sign Up</p>
                        </div>
                        <div class="col-sm">
                            <i class="fas fa-paw fa-3x"></i>
                            <p><strong>2:</strong> Create Pet Profile</p>
                        </div>
                        <div class="col-sm">
                            <i class="fas fa-tasks fa-3x"></i>
                            <p><strong>3:</strong> Add Vaccines</p>
                        </div>
                    </div>
                </div>

                <!-- Button trigger modal -->
                <button type="button" class="btn btn-flat" data-toggle="modal" data-target="#exampleModal">
                    Get Started for Free!
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-md modal-dialog-centered modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Getting Started</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                {% if user.is_authenticated %}
                                <a class="btn btn-flat" href="{% url 'profile-add' %}">Create Pet Profile</a>
                                {% else %}
                                <a class="btn btn-flat" href="{% url 'signup'%}?next={{request.path}}">Signup</a>
                                {% endif %}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="footer">
    <!--   <div class="footer-links">
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            </div> -->
    <div class="footer-copyright">
        This site was made with <i class="fas fa-heart"></i> by Health Passport
        <!-- <div>Icons made by <a href="https://www.flaticon.local/authors/freepik" title="Freepik">Freepik</a> from <a
                href="https://www.flaticon.local/" title="Flaticon">www.flaticon.local</a></div> -->
    </div>
</div>

app/templates/app/profile_create_form.html
{% include 'app/partials/base.html' %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="cards-show m-5">
        <h5 class="card-header text-center">
            <strong>Add New Pet Profile</strong>
        </h5>
        <form enctype="multipart/form-data" class='form-format' method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-flat" type="submit" value="Save">
        </form>
    </div>
    <hr>
    <a class="btn btn-flat" href="{% url 'profiles' %}">Back to Family</a>
</div>

app/templates/app/profile_delete_form.html
{% include 'app/partials/base.html' %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="cards-show m-5">
        <h5 class="card-header text-center">
            <strong>Delete Member Profile for {{ object }}</strong>
        </h5>
        <form class='form-format' method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm">
        </form>
    </div>
    <hr>
    <a class="btn btn-flat" href="{% url 'profiles' %}">Back to Family</a>
</div>

app/templates/app/profile_detail.html
{% include 'app/partials/base.html' %}

<div class="banner"
    style="padding: 100px 0; background-image: linear-gradient(rgba(0,0,0,0.0),rgba(0,0,0,0.2)),
    url(https://images.unsplash.com/photo-1534361960057-19889db9621e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80);">
    <div class="container">
        <div class="cards">
            <div class="card-profile">
                <h1>{{ profile.pet_name }} Profile</h1>
                <p>Personal data, health and vaccination / immunization information</p>
                <!-- <a class="btn btn-flat" href="{% url 'profile-update' profile.id %}">Upload Vaccination Card</a> -->
                <a class="btn btn-flat" href="{% url 'sendmail' %}">Set up Alerts & Reminders</a>
            </div>
            {% for immunization in profile.immunization_set.all %}
            {% if immunization.vaccine_expired %}
            <div class="card-profile-warning">
                <i class="fas fa-exclamation-triangle mt-3"></i>
                <h4>Vaccination Alerts / Reminders</h4>
                <h5>{{ immunization.vaccine.vaccine_name }} Expired: {{ immunization.expired_by }}</h5>
            </div>
            {% else %}
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

<div class="container">
    <div class="cards">
        <div class="card">
            <h5 class="card-header"><strong>Personal Information</strong></h5>
            <div class="card-body">
                <ul class="list-inline-profile">
                    <li><strong>Pet Name:</strong> {{ profile.pet_name }}</li>
                    <li><strong>Pet Microchip Id:</strong> {{ profile.pet_microchip_id }}</li>
                    <li><strong>Date of Birth:</strong> {{ profile.date_of_birth }}</li>
                    <li><strong>Age:</strong> {{profile.calculate_age}}</li>
                    <li><strong>Doctor Name & Contact:</strong> {{ profile.doctor_name_contact }}</li>
                    <li><strong>Family Member:</strong> {{ profile.family_member_type }}</li>
                </ul>
                <a class="btn btn-flat" href="{% url 'profile-update' profile.id %}"> Edit Profile</a>
            </div>
        </div>


        <div class="card">
            <h5 class="card-header"><strong>Vaccinations / Immunizations</strong></h5>
            <div class="card-body">
                {% for immunization in profile.immunization_set.all %}
                <div class="notification">
                    <div class="notification-content text-left">
                        <p><a href="{{ immunization.get_absolute_url }}">
                                {{ immunization.vaccine.vaccine_name }}
                            </a></p>
                        <p><small>Expires: {{ immunization.expired_by }}</small></p>
                    </div>
                    <div class="notification-actions">
                        <a href="{% url 'immunization-update' immunization.id %}"> Edit
                            <i class=" fas fa-pencil-alt"></i>
                        </a>
                        <a href="{% url 'immunization-delete' immunization.id %}"> Delete
                            <i class="far fa-trash-alt"></i>
                        </a>
                    </div>
                </div>
                {% endfor %}
                <br>
                <a class="btn btn-flat" href="{% url 'immunization-add' %}"> Add Immunization</a>
            </div>
        </div>

    </div>
    <hr>
    <a class="btn btn-flat" href="{% url 'profiles' %}">Back to Family</a>
</div>

app/templates/app/profile_list.html
{% include 'app/partials/base.html' %}
{% load static %}

<div class="banner-manage">
    <div class="container text-center">
        {% for profile in profile_list %}
        {% if forloop.first %}
        <h1>{{ profile.family_name }} Family</h1>
        {% endif %}
        {% endfor %}
        <p>View Family Member Profiles</p>
        <a class="btn btn-flat" href="{% url 'profile-add' %}"> Add Profile</a>
    </div>
</div>

{% if profile_list %}

<div class="profile-wrapper mt-5">
    {% for profile in profile_list %}
    <div class="notification">
        <img src="{% static 'images/cat.png' %}" alt="Avatar" class="avatar-large" />
        <div class="notification-content">
            <p><strong>Pet Name:</strong><a href="{{ profile.get_absolute_url }}">
                    {{ profile.pet_name }}
                </a></p>
            <p><strong>Family Member Type:</strong> {{ profile.family_member_type }}</p>
        </div>

        <div class="notification-actions color: ">
            <a href="{% url 'profile-update' profile.id %}">Edit <i class="fas fa-pencil-alt"></i></a>
            <a href="{% url 'profile-delete' profile.id %}">Delete <i class="far fa-trash-alt"></i></a>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="text-center mt-5">
        <p>No Profiles Exist</p>
    </div>
    {% endif %}
    <hr>
</div>

app/templates/app/profile_update_form.html
{% include 'app/partials/base.html' %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="cards-show m-5">
        <h5 class="card-header text-center">
            <strong>Update Member Profile for {{ object }}</strong>
        </h5>
        <form enctype="multipart/form-data" class='form-format' method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-flat" type="submit" value="Update">
        </form>
    </div>
    <hr>
    <a class="btn btn-flat" href="{% url 'profiles' %}">Back to Family</a>
</div>

app/templates/app/vaccine_create_form.html
{% include 'app/partials/base.html' %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="cards-show m-5">
        <h5 class="card-header text-center">
            <strong>Add New Vaccine</strong>
        </h5>
        <form class='form-format' method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-flat" type="submit" value="Save">
        </form>
    </div>
    <hr>
    <a class="btn btn-flat" href="{% url 'vaccines' %}">Back to Vaccine Repository</a>
</div>

app/templates/app/vaccine_detail.html
{% include 'app/partials/base.html' %}

<div class="container">
    <div class="cards-show">
        <div class="card">
            <h5 class="card-header"><strong>{{ vaccine.vaccine_name }} Vaccine Detail</strong>
            </h5>
            <div class="card-body">
                <ul class="list-inline-profile">
                    <li><strong>Name:</strong> {{ vaccine.vaccine_name }}</li>
                    <li><strong>Disease Type:</strong> {{ vaccine.disease_type }}</li>
                </ul>
            </div>
        </div>
    </div>
    <hr>
    <a class="btn btn-flat" href="{% url 'vaccines' %}">Back to Vaccine List</a>

app/templates/app/vaccine_update_form.html
{% include 'app/partials/base.html' %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="cards-show m-5">
        <h5 class="card-header text-center">
            <strong>Update {{ object }}</strong>
        </h5>
        <form class='form-format' method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-flat" type="submit" value="Update">
        </form>
    </div>
    <hr>
    <a class="btn btn-flat" href="{% url 'vaccines' %}">Back to Vaccine Repository</a>
</div>